### ISSUE TITLE
Pruebas de aceptacion para el inicio de sesion con microsoft

### ISSUE THREAD

**Issue by daniellupaca** [UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-pruebas-2-rivera-lupaca#3]
Se realizó una prueba de funcionalidad para verificar que el botón "Login with Microsoft" en la interfaz de login de la aplicación Flutter está presente y funciona correctamente.

**Comment by JhonnyARM** [comment]
Se añadio lo siguiente:
- Pruebas de intefaz para login con microsoft
- Diagrama del pipeline
- Diagrama de flujo para las pruebas
- CI/CD
- Reporte usando GitHub Pages

**Comment by JhonnyARM** [comment]
Se añadio lo siguiente:

- [x] Pruebas de intefaz para login con microsoft
- [X] Diagrama del pipeline
- [X] Diagrama de flujo para las pruebas
- [X] CI/CD
- [X] Reporte usando GitHub Pages
